<a href="https://colab.research.google.com/github/ShashikanthKungulwar/DL/blob/main/Linear_regression_scratch_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

inputs = np.array([
      [73, 67,43],
      [91, 88, 64],
      [87, 134, 58],
      [102, 43, 37],
      [69, 96, 70]
],dtype=np.float32)


targets = np.array(
    [
      [56, 70],
      [81, 101],
      [119, 113],
      [22, 37],
      [103, 119]
    ],
    dtype=np.float32
)

In [ ]:
import torch

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
weights = torch.randn(2,3,requires_grad = True)
bias = torch.randn(2,requires_grad=True)

print(weights.shape)
print(bias.shape)


torch.Size([2, 3])
torch.Size([2])


In [ ]:
def model(x):
  return x@weights.T + bias

In [ ]:
def MSE(y_pred,y_true):
  diff = y_pred - y_true
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
for i in range(100):
  pred = model(inputs)
  loss = MSE(pred,targets)
  loss.backward()
  print(loss)
  with torch.no_grad():
    lr = 1e-5
    weights -= weights.grad * lr
    bias -= bias.grad * lr
    weights.grad.zero_()
    bias.grad.zero_()

tensor(45001.4102, grad_fn=<DivBackward0>)
tensor(30567.3164, grad_fn=<DivBackward0>)
tensor(20838.0918, grad_fn=<DivBackward0>)
tensor(14279.4395, grad_fn=<DivBackward0>)
tensor(9857.4180, grad_fn=<DivBackward0>)
tensor(6875.2656, grad_fn=<DivBackward0>)
tensor(4863.4502, grad_fn=<DivBackward0>)
tensor(3505.5554, grad_fn=<DivBackward0>)
tensor(2588.3542, grad_fn=<DivBackward0>)
tensor(1968.1570, grad_fn=<DivBackward0>)
tensor(1548.1305, grad_fn=<DivBackward0>)
tensor(1263.0217, grad_fn=<DivBackward0>)
tensor(1068.8561, grad_fn=<DivBackward0>)
tensor(936.0004, grad_fn=<DivBackward0>)
tensor(844.4847, grad_fn=<DivBackward0>)
tensor(780.8512, grad_fn=<DivBackward0>)
tensor(736.0302, grad_fn=<DivBackward0>)
tensor(703.9102, grad_fn=<DivBackward0>)
tensor(680.3717, grad_fn=<DivBackward0>)
tensor(662.6390, grad_fn=<DivBackward0>)
tensor(648.8409, grad_fn=<DivBackward0>)
tensor(637.7162, grad_fn=<DivBackward0>)
tensor(628.4148, grad_fn=<DivBackward0>)
tensor(620.3635, grad_fn=<DivBackward0>)

Saininty tests


In [ ]:
pred = model(inputs)
pred

tensor([[  8.3596, -46.2780],
        [ -0.7517, -56.8152],
        [ -0.6141, -89.4517],
        [ 38.3841, -38.3877],
        [-24.3625, -55.3250]], grad_fn=<AddBackward0>)

In [ ]:
loss =  MSE(pred,targets)
loss
loss.backward()

In [ ]:
weights.grad

tensor([[ -5688.0850,  -7587.3281,  -4505.4868],
        [-12036.1484, -13756.7529,  -8366.8838]])

In [ ]:
bias.grad

tensor([ -71.9969, -145.2515])

In [ ]:
weights.grad.zero_()
bias.grad.zero_()

tensor([0., 0.])

In [ ]:
weights.grad

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
bias.grad

tensor([0., 0.])

In [ ]:
loss = MSE(model(inputs),targets)
loss.backward()

In [ ]:
weights.grad

tensor([[ -5688.0850,  -7587.3281,  -4505.4868],
        [-12036.1484, -13756.7529,  -8366.8838]])

In [ ]:
bias.grad

tensor([ -71.9969, -145.2515])

In [ ]:
(inputs@weights.T).shape

torch.Size([5, 2])

In [ ]:
(inputs@weights.T)

tensor([[263.1868,   9.3785],
        [358.3470,   9.6915],
        [385.3384,  27.6384],
        [259.2623,   3.4463],
        [354.5446,  10.1593]], grad_fn=<MmBackward0>)

In [ ]:
inputs@weights.T + bias

tensor([[264.2315,   8.2950],
        [359.3917,   8.6080],
        [386.3831,  26.5549],
        [260.3070,   2.3628],
        [355.5892,   9.0758]], grad_fn=<AddBackward0>)

In [ ]:
bias

tensor([ 1.0447, -1.0835], requires_grad=True)